# Contoh isi main.yml
name: PHP Code Standards Check
on: [push]
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0" # Sesuaikan versi PHP jika perlu
          tools: phpcs
      - run: phpcs --standard=PSR12 .
